[package]
name = "maki-fs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
description = "Filesystem adapter for Maki projects"

[dependencies]
maki-core = { version = "0.1.0", path = "../maki-core" }
