[package]
name = "maki"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
description = "Line-first markup language and personal wiki runtime"
readme = "README.md"

[workspace]
members = [
    "crates/maki-core",
    "crates/maki-http",
    "crates/maki-lsp",
    "crates/maki-serve",
]

[workspace.package]
version = "0.1.0"
authors = ["An Nyeong <me@annyeong.me>"]
edition = "2024"
license = "MIT"
repository = "https://git.eska.nyeong.me/nyeong/maki"
homepage = "https://git.eska.nyeong.me/nyeong/maki"
publish = false

[dependencies]
maki-core = { version = "0.1.0", path = "crates/maki-core" }
maki-lsp = { version = "0.1.0", path = "crates/maki-lsp" }
maki-serve = { version = "0.1.0", path = "crates/maki-serve" }
serde_json = "1.0"
