[package]
name = "maki"
version = "0.1.0"
authors = ["An Nyeong <me@annyeong.me>"]
edition = "2024"
description = "File based markdown wiki"
readme = "README.md"

[workspace]
members = [
    "crates/maki-core",
    "crates/maki-serve",
]

[dependencies]
maki-core = { path = "crates/maki-core" }
maki-serve = { path = "crates/maki-serve" }
