[package]
name = "maki-serve"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
description = "Web serving and Git-backed project support for Maki"

[dependencies]
maki-core = { version = "0.1.0", path = "../maki-core" }
maki-http = { version = "0.1.0", path = "../maki-http" }
percent-encoding = "2.3.2"
