[package]
name = "maki-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
description = "Core parsing and project analysis for Maki"

[dependencies]
ureq = { version = "2.12.1", default-features = false, features = ["tls"] }
